<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Sentra.Intelligence</RootNamespace>
    <AssemblyName>Sentra.Intelligence</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Sentra.Application\Sentra.Application.csproj" />
  </ItemGroup>
</Project>
